- name: 安装依赖
  apt:
    name:
      - gcc
      - make
      - libpcre3
      - libpcre3-dev
      - zlib1g-dev
      - openssl
      - libssl-dev
      - libxslt-dev
      - libgd-dev
      - libgeoip-dev
      - apache2-utils
      - libperl-dev
      - build-essential
      - clang
      - llvm-dev
      - libclang-dev
      - libc6-dev
      - gcc-multilib
    state: present
    update_cache: yes
- name: 创建源码目录
  file:
    state: directory
    path: /root/mknginx/
- name: 下载源码
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - {'url': 'https://nginx.org/download/nginx-{{ nginxVersion }}.tar.gz', 'dest': '/root/mknginx/nginx-{{ nginxVersion }}.tar.gz'}
    - {'url': 'https://github.com/nginx/nginx-acme/releases/download/v{{ nginxAcmeVersion }}/nginx-acme-{{ nginxAcmeVersion }}.tar.gz', 'dest': '/root/mknginx/nginx-acme-{{ nginxAcmeVersion }}.tar.gz'}
- name: 解压源码
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  loop:
    - {'src': '/root/mknginx/nginx-{{ nginxVersion }}.tar.gz', 'dest': '/root/mknginx/' }
    - {'src': '/root/mknginx/nginx-acme-{{ nginxAcmeVersion }}.tar.gz', 'dest': '/root/mknginx/' }
- name: 安装cargo
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  args:
    executable: /bin/bash
- name: 创建目录
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - /var/lib/nginx/
    - /var/cache/nginx/
    - /etc/nginx/conf.d/
    - /usr/share/nginx/acme/letsencrypt/
- name: 准备编译参数
  ansible.builtin.shell: 
    chdir: /root/mknginx/nginx-{{ nginxVersion }}
    cmd: |
      source $HOME/.cargo/env
      ./configure --prefix=/usr/share/nginx  --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log \
      --error-log-path=/var/log/nginx/error.log  --lock-path=/var/lock/nginx.lock  --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules \
      --http-client-body-temp-path=/var/lib/nginx/body  --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy \
      --http-scgi-temp-path=/var/lib/nginx/scgi  --http-uwsgi-temp-path=/var/lib/nginx/uwsgi  --with-compat --with-debug --with-pcre-jit \
      --with-http_ssl_module --with-http_stub_status_module  --with-http_realip_module --with-http_auth_request_module --with-http_v2_module \
      --with-http_dav_module  --with-http_slice_module --with-threads --with-http_addition_module --with-http_flv_module --with-http_gunzip_module \
      --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_secure_link_module    --with-http_sub_module \
      --with-mail_ssl_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_realip_module --with-http_geoip_module=dynamic \
      --with-http_image_filter_module=dynamic  --with-http_perl_module=dynamic --with-http_xslt_module=dynamic --with-mail=dynamic --with-stream=dynamic \
      --with-stream_geoip_module=dynamic \
      --add-dynamic-module=/root/mknginx/nginx-acme-{{ nginxAcmeVersion }}
    executable: /bin/bash
- name: 编译安装nginx
  ansible.builtin.shell:
    chdir: /root/mknginx/nginx-{{ nginxVersion }}
    cmd: "make -j $(nproc) && make install"
- name: 创建软连接
  file:
    src: /usr/share/nginx/sbin/nginx
    dest: /usr/sbin/nginx
    state: link
- name: 渲染配置文件
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: nginx.service.j2
      dest: /usr/lib/systemd/system/nginx.service
    - src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    - src: vhost.conf.j2
      dest: "/etc/nginx/conf.d/{{ domain.split('.')[0] }}.conf"
  notify:
    - Restart Nginx