- name: 安装 podman
  apt:
    name: podman
    state:  present
- name: 创建vaultwarden数据目录
  ansible.builtin.shell:
    podman volume create vaultwarden
- name: 运行vaultwarden
  ansible.builtin.shell:
     podman run -d  --name vaultwarden \
      --volume vaultwarden:/data \
      -p 127.0.0.1:8001:80  \
      -e SIGNUPS_ALLOWED=false \
      -e DATABASE_URL=/data/bitwarden.db \
      -e ROCKET_WORKERS=1 \
      -e WEB_VAULT_ENABLED=true \
      -e WEBSOCKET_ENABLED=true \
      --restart=always docker.io/vaultwarden/server:{{ vaultwardenVersion }}-alpine
